-- ============================================================
-- TWL PORTAL 360LIFE - TENANT DATABASE
-- FILE: 02_Agents.sql
-- ============================================================
GO

CREATE TABLE DaiLy (
    Id                      UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    DoiTacId                UNIQUEIDENTIFIER  NOT NULL,
    NguoiDungId             UNIQUEIDENTIFIER  NOT NULL,
    MaDaiLy                 NVARCHAR(50)      NOT NULL,
    HoTen                   NVARCHAR(255)     NOT NULL,
    NgaySinh                DATE              NULL,
    GioiTinh                NVARCHAR(10)      NULL,
    UrlAnhDaiDien           NVARCHAR(500)     NULL,
    SoDienThoai             NVARCHAR(20)      NOT NULL,
    SdtPhu                  NVARCHAR(20)      NULL,
    Email                   NVARCHAR(255)     NOT NULL,
    ZaloId                  NVARCHAR(100)     NULL,
    SoCMND                  NVARCHAR(20)      NOT NULL,
    NgayCapCMND             DATE              NULL,
    NoiCapCMND              NVARCHAR(255)     NULL,
    UrlMatTruocCMND         NVARCHAR(500)     NULL,
    UrlMatSauCMND           NVARCHAR(500)     NULL,
    DiaChiThuongTru         NVARCHAR(500)     NULL,
    DiaChiHienTai           NVARCHAR(500)     NULL,
    TinhThanh               NVARCHAR(100)     NULL,
    QuanHuyen               NVARCHAR(100)     NULL,
    DonViToChucId           UNIQUEIDENTIFIER  NULL REFERENCES DonViToChuc(Id),
    CapBacId                UNIQUEIDENTIFIER  NULL REFERENCES CapBacDaiLy(Id),
    DaiLyChaId              UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    DaiLyCapTren2Id         UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    DaiLyCapTren3Id         UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    DuongDanPhanCap         NVARCHAR(500)     NULL,
    SoGiayPhep              NVARCHAR(100)     NULL,
    LoaiGiayPhep            NVARCHAR(50)      NULL,
    NgayCapGiayPhep         DATE              NULL,
    NgayHetHanGiayPhep      DATE              NULL,
    UrlFileGiayPhep         NVARCHAR(500)     NULL,
    TenNganHang             NVARCHAR(100)     NULL,
    MaNganHang              NVARCHAR(20)      NULL,
    SoTaiKhoan              NVARCHAR(50)      NULL,
    TenTaiKhoan             NVARCHAR(255)     NULL,
    ChiNhanhNganHang        NVARCHAR(200)     NULL,
    KinhNghiemTruoc         NVARCHAR(MAX)     NULL,
    TrinhDoHocVan           NVARCHAR(50)      NULL,
    ChuyenMon               NVARCHAR(255)     NULL,
    TenMienCaNhan           NVARCHAR(100)     NULL,
    TrangDichCaNhanId       UNIQUEIDENTIFIER  NULL,
    DaiLyTuyenDungId        UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    NgayTuyenDung           DATE              NULL,
    NgayThamGia             DATE              NULL,
    MucTieuDoanhThuThang    DECIMAL(18,2)     NULL,
    MucTieuDoanhThuNam      DECIMAL(18,2)     NULL,
    MucTieuHopDongThang     INT               NULL,
    DoanhThuLuyKeToanBo     DECIMAL(18,2)     NOT NULL DEFAULT 0,
    DoanhThuThangHienTai    DECIMAL(18,2)     NOT NULL DEFAULT 0,
    DoanhThuNamHienTai      DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TongHopDongLuyKe        INT               NOT NULL DEFAULT 0,
    TongHopDongThang        INT               NOT NULL DEFAULT 0,
    TongKhachHang           INT               NOT NULL DEFAULT 0,
    TongDaiLyCapDuoi        INT               NOT NULL DEFAULT 0,
    LanCapNhatThongKeCuoi   DATETIME2         NULL,
    TrangThai               NVARCHAR(20)      NOT NULL DEFAULT 'ACTIVE',
    TrangThaiOnboard        NVARCHAR(30)      NOT NULL DEFAULT 'INCOMPLETE',
    NgayNghiViec            DATE              NULL,
    LyDoNghiViec            NVARCHAR(500)     NULL,
    GhiChu                  NVARCHAR(MAX)     NULL,
    GhiChuNoiBo             NVARCHAR(MAX)     NULL,
    NgayTao                 DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    NguoiTao                UNIQUEIDENTIFIER  NULL,
    NgayCapNhat             DATETIME2         NULL,
    NguoiCapNhat            UNIQUEIDENTIFIER  NULL,
    CONSTRAINT PK_DaiLy PRIMARY KEY (Id),
    CONSTRAINT UQ_DaiLy_Ma UNIQUE (DoiTacId, MaDaiLy),
    CONSTRAINT UQ_DaiLy_NguoiDung UNIQUE (NguoiDungId)
);
GO

CREATE TABLE LichSuCapBacDaiLy (
    Id                BIGINT            NOT NULL IDENTITY(1,1),
    DaiLyId           UNIQUEIDENTIFIER  NOT NULL REFERENCES DaiLy(Id),
    CapBacCuId        UNIQUEIDENTIFIER  NULL REFERENCES CapBacDaiLy(Id),
    CapBacMoiId       UNIQUEIDENTIFIER  NOT NULL REFERENCES CapBacDaiLy(Id),
    LoaiThayDoi       NVARCHAR(20)      NOT NULL,
    LyDoThayDoi       NVARCHAR(500)     NULL,
    GhiChuMinhChung   NVARCHAR(MAX)     NULL,
    NguoiThayDoi      UNIQUEIDENTIFIER  NULL,
    NgayThayDoi       DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    HieuLucTu         DATE              NOT NULL,
    CONSTRAINT PK_LichSuCapBacDaiLy PRIMARY KEY (Id)
);
GO
