-- ============================================================
-- TWL PORTAL 360LIFE - TENANT DATABASE
-- FILE: 02_Agents.sql
-- ============================================================
GO

CREATE TABLE Agents (
    Id                    UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    TenantId              UNIQUEIDENTIFIER  NOT NULL,
    UserId                UNIQUEIDENTIFIER  NOT NULL,
    AgentCode             NVARCHAR(50)      NOT NULL,
    FullName              NVARCHAR(255)     NOT NULL,
    DateOfBirth           DATE              NULL,
    Gender                NVARCHAR(10)      NULL,
    AvatarUrl             NVARCHAR(500)     NULL,
    Phone                 NVARCHAR(20)      NOT NULL,
    PhoneSecondary        NVARCHAR(20)      NULL,
    Email                 NVARCHAR(255)     NOT NULL,
    ZaloId                NVARCHAR(100)     NULL,
    IdCardNumber          NVARCHAR(20)      NOT NULL,
    IdCardIssuedDate      DATE              NULL,
    IdCardIssuedPlace     NVARCHAR(255)     NULL,
    IdCardFrontUrl        NVARCHAR(500)     NULL,
    IdCardBackUrl         NVARCHAR(500)     NULL,
    PermanentAddress      NVARCHAR(500)     NULL,
    CurrentAddress        NVARCHAR(500)     NULL,
    Province              NVARCHAR(100)     NULL,
    District              NVARCHAR(100)     NULL,
    OrgUnitId             UNIQUEIDENTIFIER  NULL REFERENCES OrgUnits(Id),
    RankId                UNIQUEIDENTIFIER  NULL REFERENCES AgentRanks(Id),
    ParentAgentId         UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    UplineL2AgentId       UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    UplineL3AgentId       UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    HierarchyPath         NVARCHAR(500)     NULL,
    LicenseNumber         NVARCHAR(100)     NULL,
    LicenseType           NVARCHAR(50)      NULL,
    LicenseIssuedDate     DATE              NULL,
    LicenseExpiryDate     DATE              NULL,
    LicenseFileUrl        NVARCHAR(500)     NULL,
    BankName              NVARCHAR(100)     NULL,
    BankCode              NVARCHAR(20)      NULL,
    BankAccountNumber     NVARCHAR(50)      NULL,
    BankAccountName       NVARCHAR(255)     NULL,
    BankBranch            NVARCHAR(200)     NULL,
    PreviousExperience    NVARCHAR(MAX)     NULL,
    EducationLevel        NVARCHAR(50)      NULL,
    Specialization        NVARCHAR(255)     NULL,
    PersonalSubdomain     NVARCHAR(100)     NULL,
    PersonalLandingPageId UNIQUEIDENTIFIER  NULL,
    RecruitedByAgentId    UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    RecruitedAt           DATE              NULL,
    JoinDate              DATE              NULL,
    MonthlyRevenueTarget  DECIMAL(18,2)     NULL,
    YearlyRevenueTarget   DECIMAL(18,2)     NULL,
    MonthlyPolicyTarget   INT               NULL,
    TotalRevenueLTD       DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TotalRevenueMTD       DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TotalRevenueYTD       DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TotalPoliciesLTD      INT               NOT NULL DEFAULT 0,
    TotalPoliciesMTD      INT               NOT NULL DEFAULT 0,
    TotalCustomers        INT               NOT NULL DEFAULT 0,
    TotalDownlineAgents   INT               NOT NULL DEFAULT 0,
    LastStatsUpdatedAt    DATETIME2         NULL,
    Status                NVARCHAR(20)      NOT NULL DEFAULT 'ACTIVE',
    OnboardingStatus      NVARCHAR(30)      NOT NULL DEFAULT 'INCOMPLETE',
    TerminatedAt          DATE              NULL,
    TerminateReason       NVARCHAR(500)     NULL,
    Notes                 NVARCHAR(MAX)     NULL,
    InternalNotes         NVARCHAR(MAX)     NULL,
    CreatedAt             DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy             UNIQUEIDENTIFIER  NULL,
    UpdatedAt             DATETIME2         NULL,
    UpdatedBy             UNIQUEIDENTIFIER  NULL,
    CONSTRAINT PK_Agents PRIMARY KEY (Id),
    CONSTRAINT UQ_Agents_Code UNIQUE (TenantId, AgentCode),
    CONSTRAINT UQ_Agents_UserId UNIQUE (UserId)
);
GO

CREATE TABLE AgentRankHistory (
    Id              BIGINT            NOT NULL IDENTITY(1,1),
    AgentId         UNIQUEIDENTIFIER  NOT NULL REFERENCES Agents(Id),
    OldRankId       UNIQUEIDENTIFIER  NULL REFERENCES AgentRanks(Id),
    NewRankId       UNIQUEIDENTIFIER  NOT NULL REFERENCES AgentRanks(Id),
    ChangeType      NVARCHAR(20)      NOT NULL,
    ChangeReason    NVARCHAR(500)     NULL,
    EvidenceNote    NVARCHAR(MAX)     NULL,
    ChangedBy       UNIQUEIDENTIFIER  NULL,
    ChangedAt       DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    EffectiveFrom   DATE              NOT NULL,
    CONSTRAINT PK_AgentRankHistory PRIMARY KEY (Id)
);
GO
