-- ============================================================
-- TWL PORTAL 360LIFE - TENANT DATABASE
-- FILE: 03_Customers_CRM.sql
-- ============================================================
GO

CREATE TABLE Customers (
    Id                      UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    TenantId                UNIQUEIDENTIFIER  NOT NULL,
    CustomerCode            NVARCHAR(50)      NOT NULL,
    CustomerType            NVARCHAR(20)      NOT NULL DEFAULT 'GUEST',
    UserId                  UNIQUEIDENTIFIER  NULL,
    FullName                NVARCHAR(255)     NOT NULL,
    DateOfBirth             DATE              NULL,
    Gender                  NVARCHAR(10)      NULL,
    IdCardType              NVARCHAR(20)      NULL,
    IdCardNumber            NVARCHAR(20)      NULL,
    IdCardIssuedDate        DATE              NULL,
    IdCardIssuedPlace       NVARCHAR(255)     NULL,
    Phone                   NVARCHAR(20)      NOT NULL,
    PhoneSecondary          NVARCHAR(20)      NULL,
    Email                   NVARCHAR(255)     NULL,
    ZaloId                  NVARCHAR(100)     NULL,
    Address                 NVARCHAR(500)     NULL,
    Ward                    NVARCHAR(100)     NULL,
    District                NVARCHAR(100)     NULL,
    Province                NVARCHAR(100)     NULL,
    Occupation              NVARCHAR(100)     NULL,
    OccupationCode          NVARCHAR(20)      NULL,
    CompanyName             NVARCHAR(255)     NULL,
    AssetInfo               NVARCHAR(MAX)     NULL,
    LookupToken             NVARCHAR(100)     NULL,
    LookupTokenExpiry       DATETIME2         NULL,
    CustomerSegment         NVARCHAR(30)      NULL,
    LeadScore               INT               NOT NULL DEFAULT 0,
    Tags                    NVARCHAR(MAX)     NULL,
    Source                  NVARCHAR(50)      NULL,
    SourceDetail            NVARCHAR(255)     NULL,
    ReferralAgentId         UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    ReferralCustomerId      UNIQUEIDENTIFIER  NULL REFERENCES Customers(Id),
    LandingPageId           UNIQUEIDENTIFIER  NULL,
    UtmSource               NVARCHAR(100)     NULL,
    UtmMedium               NVARCHAR(100)     NULL,
    UtmCampaign             NVARCHAR(100)     NULL,
    UtmContent              NVARCHAR(100)     NULL,
    AssignedAgentId         UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    AssignedAt              DATETIME2         NULL,
    InsuranceNeeds          NVARCHAR(MAX)     NULL,
    BudgetRange             NVARCHAR(50)      NULL,
    PreferredContactTime    NVARCHAR(100)     NULL,
    PreferredContactChannel NVARCHAR(50)      NULL,
    TotalPolicies           INT               NOT NULL DEFAULT 0,
    ActivePolicies          INT               NOT NULL DEFAULT 0,
    TotalPremiumPaid        DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TotalPremiumAnnual      DECIMAL(18,2)     NOT NULL DEFAULT 0,
    LoyaltyPoints           INT               NOT NULL DEFAULT 0,
    LastPurchaseAt          DATETIME2         NULL,
    LastContactAt           DATETIME2         NULL,
    UpgradedToMemberAt      DATETIME2         NULL,
    Notes                   NVARCHAR(MAX)     NULL,
    InternalNotes           NVARCHAR(MAX)     NULL,
    IsActive                BIT               NOT NULL DEFAULT 1,
    IsBlacklisted           BIT               NOT NULL DEFAULT 0,
    BlacklistReason         NVARCHAR(500)     NULL,
    CreatedAt               DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt               DATETIME2         NULL,
    CONSTRAINT PK_Customers PRIMARY KEY (Id),
    CONSTRAINT UQ_Customers_Code UNIQUE (TenantId, CustomerCode)
);
GO

CREATE TABLE CustomerContactHistory (
    Id                BIGINT            NOT NULL IDENTITY(1,1),
    CustomerId        UNIQUEIDENTIFIER  NOT NULL REFERENCES Customers(Id),
    TenantId          UNIQUEIDENTIFIER  NOT NULL,
    AgentId           UNIQUEIDENTIFIER  NULL REFERENCES Agents(Id),
    ContactType       NVARCHAR(20)      NOT NULL,
    Direction         NVARCHAR(10)      NULL,
    Duration          INT               NULL,
    Subject           NVARCHAR(500)     NULL,
    Content           NVARCHAR(MAX)     NULL,
    Outcome           NVARCHAR(50)      NULL,
    FollowUpDate      DATETIME2         NULL,
    FollowUpNote      NVARCHAR(500)     NULL,
    RelatedPipelineId UNIQUEIDENTIFIER  NULL,
    RelatedPolicyId   UNIQUEIDENTIFIER  NULL,
    IsSystemGenerated BIT               NOT NULL DEFAULT 0,
    CreatedAt         DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy         UNIQUEIDENTIFIER  NULL,
    CONSTRAINT PK_CustomerContactHistory PRIMARY KEY (Id)
);
GO

CREATE TABLE CustomerDocuments (
    Id              UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    CustomerId      UNIQUEIDENTIFIER  NOT NULL REFERENCES Customers(Id),
    TenantId        UNIQUEIDENTIFIER  NOT NULL,
    DocType         NVARCHAR(50)      NOT NULL,
    DocName         NVARCHAR(255)     NULL,
    FileUrl         NVARCHAR(500)     NOT NULL,
    FileSize        BIGINT            NULL,
    MimeType        NVARCHAR(100)     NULL,
    RelatedPolicyId UNIQUEIDENTIFIER  NULL,
    UploadedBy      UNIQUEIDENTIFIER  NULL,
    UploadedAt      DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    IsVerified      BIT               NOT NULL DEFAULT 0,
    VerifiedBy      UNIQUEIDENTIFIER  NULL,
    VerifiedAt      DATETIME2         NULL,
    ExpiryDate      DATE              NULL,
    IsActive        BIT               NOT NULL DEFAULT 1,
    CONSTRAINT PK_CustomerDocuments PRIMARY KEY (Id)
);
GO
