-- ============================================================
-- TWL PORTAL 360LIFE - TENANT DATABASE
-- FILE: 03_Customers_CRM.sql
-- ============================================================
GO

CREATE TABLE KhachHang (
    Id                      UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    DoiTacId                UNIQUEIDENTIFIER  NOT NULL,
    MaKhachHang             NVARCHAR(50)      NOT NULL,
    LoaiKhachHang           NVARCHAR(20)      NOT NULL DEFAULT 'GUEST',
    NguoiDungId             UNIQUEIDENTIFIER  NULL,
    HoTen                   NVARCHAR(255)     NOT NULL,
    NgaySinh                DATE              NULL,
    GioiTinh                NVARCHAR(10)      NULL,
    LoaiGiayTo              NVARCHAR(20)      NULL,
    SoGiayTo                NVARCHAR(20)      NULL,
    NgayCapGiayTo           DATE              NULL,
    NoiCapGiayTo            NVARCHAR(255)     NULL,
    SoDienThoai             NVARCHAR(20)      NOT NULL,
    SdtPhu                  NVARCHAR(20)      NULL,
    Email                   NVARCHAR(255)     NULL,
    ZaloId                  NVARCHAR(100)     NULL,
    DiaChi                  NVARCHAR(500)     NULL,
    PhuongXa                NVARCHAR(100)     NULL,
    QuanHuyen               NVARCHAR(100)     NULL,
    TinhThanh               NVARCHAR(100)     NULL,
    NgheNghiep              NVARCHAR(100)     NULL,
    MaNgheNghiep            NVARCHAR(20)      NULL,
    TenCongTy               NVARCHAR(255)     NULL,
    ThongTinTaiSan          NVARCHAR(MAX)     NULL,
    MaTraCuu                NVARCHAR(100)     NULL,
    HanMaTraCuu             DATETIME2         NULL,
    PhanKhucKH              NVARCHAR(30)      NULL,
    DiemTiemNang            INT               NOT NULL DEFAULT 0,
    NhanDan                 NVARCHAR(MAX)     NULL,
    NguonKH                 NVARCHAR(50)      NULL,
    ChiTietNguon            NVARCHAR(255)     NULL,
    DaiLyGioiThieuId        UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    KhachHangGioiThieuId    UNIQUEIDENTIFIER  NULL REFERENCES KhachHang(Id),
    TrangDichId             UNIQUEIDENTIFIER  NULL,
    UtmSource               NVARCHAR(100)     NULL,
    UtmMedium               NVARCHAR(100)     NULL,
    UtmCampaign             NVARCHAR(100)     NULL,
    UtmContent              NVARCHAR(100)     NULL,
    DaiLyPhuTrachId         UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    NgayGanDaiLy            DATETIME2         NULL,
    NhuCauBaoHiem           NVARCHAR(MAX)     NULL,
    KhoangNganSach          NVARCHAR(50)      NULL,
    ThoiGianLienHeMongMuon  NVARCHAR(100)     NULL,
    KenhLienHeMongMuon      NVARCHAR(50)      NULL,
    TongHopDong             INT               NOT NULL DEFAULT 0,
    HopDongConHieuLuc       INT               NOT NULL DEFAULT 0,
    TongPhiDaDong           DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TongPhiHangNam          DECIMAL(18,2)     NOT NULL DEFAULT 0,
    DiemTichLuy             INT               NOT NULL DEFAULT 0,
    LanMuaCuoi              DATETIME2         NULL,
    LanLienHeCuoi           DATETIME2         NULL,
    NgayLenThanhVien        DATETIME2         NULL,
    GhiChu                  NVARCHAR(MAX)     NULL,
    GhiChuNoiBo             NVARCHAR(MAX)     NULL,
    ConHoatDong             BIT               NOT NULL DEFAULT 1,
    NamTrongDanhSachDen     BIT               NOT NULL DEFAULT 0,
    LyDoDanhSachDen         NVARCHAR(500)     NULL,
    NgayTao                 DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    NgayCapNhat             DATETIME2         NULL,
    CONSTRAINT PK_KhachHang PRIMARY KEY (Id),
    CONSTRAINT UQ_KhachHang_Ma UNIQUE (DoiTacId, MaKhachHang)
);
GO

CREATE TABLE LichSuLienHeKH (
    Id                  BIGINT            NOT NULL IDENTITY(1,1),
    KhachHangId         UNIQUEIDENTIFIER  NOT NULL REFERENCES KhachHang(Id),
    DoiTacId            UNIQUEIDENTIFIER  NOT NULL,
    DaiLyId             UNIQUEIDENTIFIER  NULL REFERENCES DaiLy(Id),
    LoaiLienHe          NVARCHAR(20)      NOT NULL,
    Huong               NVARCHAR(10)      NULL,
    ThoiLuong           INT               NULL,
    ChuDe               NVARCHAR(500)     NULL,
    NoiDung             NVARCHAR(MAX)     NULL,
    KetQua              NVARCHAR(50)      NULL,
    NgayTheoDoiTiep     DATETIME2         NULL,
    GhiChuTheoDoiTiep   NVARCHAR(500)     NULL,
    QuyTrinhBanHangId   UNIQUEIDENTIFIER  NULL,
    HopDongId           UNIQUEIDENTIFIER  NULL,
    DoHeThongTao        BIT               NOT NULL DEFAULT 0,
    NgayTao             DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    NguoiTao            UNIQUEIDENTIFIER  NULL,
    CONSTRAINT PK_LichSuLienHeKH PRIMARY KEY (Id)
);
GO

CREATE TABLE TaiLieuKhachHang (
    Id              UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    KhachHangId     UNIQUEIDENTIFIER  NOT NULL REFERENCES KhachHang(Id),
    DoiTacId        UNIQUEIDENTIFIER  NOT NULL,
    LoaiTaiLieu     NVARCHAR(50)      NOT NULL,
    TenTaiLieu      NVARCHAR(255)     NULL,
    UrlFile         NVARCHAR(500)     NOT NULL,
    KichThuocFile   BIGINT            NULL,
    LoaiMime        NVARCHAR(100)     NULL,
    HopDongId       UNIQUEIDENTIFIER  NULL,
    NguoiTaiLen     UNIQUEIDENTIFIER  NULL,
    NgayTaiLen      DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    DaXacMinh       BIT               NOT NULL DEFAULT 0,
    NguoiXacMinh    UNIQUEIDENTIFIER  NULL,
    NgayXacMinh     DATETIME2         NULL,
    NgayHetHan      DATE              NULL,
    ConHoatDong     BIT               NOT NULL DEFAULT 1,
    CONSTRAINT PK_TaiLieuKhachHang PRIMARY KEY (Id)
);
GO
