-- ============================================================
-- TWL PORTAL 360LIFE - TENANT DATABASE
-- FILE: 05_Policies.sql
-- ============================================================
GO

CREATE TABLE HopDong (
    Id                   UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    DoiTacId             UNIQUEIDENTIFIER  NOT NULL,
    SoHopDong            NVARCHAR(100)     NOT NULL,
    SoHopDongNCC         NVARCHAR(100)     NULL,
    MaDoiSoat            NVARCHAR(100)     NULL,
    BaoGiaId             UNIQUEIDENTIFIER  NULL REFERENCES BaoGia(Id),
    QuyTrinhBanHangId    UNIQUEIDENTIFIER  NULL REFERENCES QuyTrinhBanHang(Id),
    SanPhamGocId         UNIQUEIDENTIFIER  NOT NULL,
    GoiSanPhamId         UNIQUEIDENTIFIER  NULL,
    NhaCungCapId         UNIQUEIDENTIFIER  NOT NULL,
    LoaiBaoHiem          NVARCHAR(50)      NOT NULL,
    KhachHangId          UNIQUEIDENTIFIER  NOT NULL REFERENCES KhachHang(Id),
    TenNguoiDuocBH       NVARCHAR(255)     NULL,
    CMNDNguoiDuocBH      NVARCHAR(20)      NULL,
    NgaySinhNguoiDuocBH  DATE              NULL,
    SdtNguoiDuocBH       NVARCHAR(20)      NULL,
    QuanHeNguoiDuocBH    NVARCHAR(50)      NULL,
    DuLieuDoiTuongBH     NVARCHAR(MAX)     NOT NULL,
    NgayBatDau           DATE              NOT NULL,
    NgayKetThuc          DATE              NOT NULL,
    SoNgayHieuLuc        INT               NOT NULL,
    PhiCoSo              DECIMAL(18,2)     NOT NULL,
    SoTienGiam           DECIMAL(18,2)     NOT NULL DEFAULT 0,
    SoTienPhuThu         DECIMAL(18,2)     NOT NULL DEFAULT 0,
    PhiCuoiCung          DECIMAL(18,2)     NOT NULL,
    SoKyThanhToan        INT               NOT NULL DEFAULT 1,
    SoTienMoiKy          DECIMAL(18,2)     NULL,
    SoTienBaoHiem        DECIMAL(18,2)     NULL,
    KenhBanHang          NVARCHAR(30)      NOT NULL,
    DaiLyId              UNIQUEIDENTIFIER  NOT NULL REFERENCES DaiLy(Id),
    TrangDichId          UNIQUEIDENTIFIER  NULL,
    TrangThaiHopDong     NVARCHAR(30)      NOT NULL DEFAULT 'DRAFT',
    NgayDoiTrangThaiHD   DATETIME2         NULL,
    NguoiDoiTrangThaiHD  UNIQUEIDENTIFIER  NULL,
    TrangThaiThanhToan   NVARCHAR(20)      NOT NULL DEFAULT 'UNPAID',
    TongDaThanhToan      DECIMAL(18,2)     NOT NULL DEFAULT 0,
    SoTienConThieu       DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TrangThaiNCC         NVARCHAR(20)      NULL,
    NgayGuiNCC           DATETIME2         NULL,
    NgayNCCXacNhan       DATETIME2         NULL,
    NgayNCCTuChoi        DATETIME2         NULL,
    LyDoNCCTuChoi        NVARCHAR(500)     NULL,
    PhanHoiNCC           NVARCHAR(MAX)     NULL,
    TrangThaiDoiSoat     NVARCHAR(30)      NULL,
    KyDoiSoat            NVARCHAR(10)      NULL,
    NgayDoiSoat          DATETIME2         NULL,
    TrangThaiHoaHong     NVARCHAR(20)      NOT NULL DEFAULT 'PENDING',
    NgayTraHoaHong       DATETIME2         NULL,
    DotChiHoaHongId      UNIQUEIDENTIFIER  NULL,
    TrangThaiTaiTuc      NVARCHAR(20)      NULL,
    HopDongTruocId       UNIQUEIDENTIFIER  NULL REFERENCES HopDong(Id),
    HopDongTaiTucId      UNIQUEIDENTIFIER  NULL REFERENCES HopDong(Id),
    NgayGuiNhacTaiTuc    DATETIME2         NULL,
    SoLanNhacTaiTuc      INT               NOT NULL DEFAULT 0,
    UrlPdfHopDong        NVARCHAR(500)     NULL,
    UrlPdfChungNhan      NVARCHAR(500)     NULL,
    UrlHoaDon            NVARCHAR(500)     NULL,
    NgayHuy              DATETIME2         NULL,
    LyDoHuy              NVARCHAR(50)      NULL,
    GhiChuHuy            NVARCHAR(500)     NULL,
    NguoiHuy             UNIQUEIDENTIFIER  NULL,
    SoTienHoanTra        DECIMAL(18,2)     NULL,
    GhiChu               NVARCHAR(MAX)     NULL,
    GhiChuNoiBo          NVARCHAR(MAX)     NULL,
    NhanDan              NVARCHAR(500)     NULL,
    NgayTao              DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    NguoiTao             UNIQUEIDENTIFIER  NULL,
    NgayCapNhat          DATETIME2         NULL,
    NguoiCapNhat         UNIQUEIDENTIFIER  NULL,
    DaXoa                BIT               NOT NULL DEFAULT 0,
    CONSTRAINT PK_HopDong PRIMARY KEY (Id),
    CONSTRAINT UQ_HopDong_SoHD UNIQUE (DoiTacId, SoHopDong)
);
GO

CREATE TABLE LichSuTrangThaiHD (
    Id                BIGINT            NOT NULL IDENTITY(1,1),
    HopDongId         UNIQUEIDENTIFIER  NOT NULL REFERENCES HopDong(Id),
    DoiTacId          UNIQUEIDENTIFIER  NOT NULL,
    TrangThaiCu       NVARCHAR(30)      NULL,
    TrangThaiMoi      NVARCHAR(30)      NOT NULL,
    LyDoThayDoi       NVARCHAR(500)     NULL,
    NguoiThayDoi      UNIQUEIDENTIFIER  NULL,
    LoaiNguoiThayDoi  NVARCHAR(20)      NULL,
    GhiChu            NVARCHAR(MAX)     NULL,
    NgayThayDoi       DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_LichSuTrangThaiHD PRIMARY KEY (Id)
);
GO

CREATE TABLE TaiLieuHopDong (
    Id             UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    HopDongId      UNIQUEIDENTIFIER  NOT NULL REFERENCES HopDong(Id),
    DoiTacId       UNIQUEIDENTIFIER  NOT NULL,
    LoaiTaiLieu    NVARCHAR(50)      NOT NULL,
    TenTaiLieu     NVARCHAR(255)     NULL,
    UrlFile        NVARCHAR(500)     NOT NULL,
    KichThuocFile  BIGINT            NULL,
    LoaiMime       NVARCHAR(100)     NULL,
    Nguon          NVARCHAR(20)      NULL,
    DaXacMinh      BIT               NOT NULL DEFAULT 0,
    NguoiTaiLen    UNIQUEIDENTIFIER  NULL,
    NgayTaiLen     DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    ConHoatDong    BIT               NOT NULL DEFAULT 1,
    CONSTRAINT PK_TaiLieuHopDong PRIMARY KEY (Id)
);
GO
