-- ============================================================
-- TWL PORTAL 360LIFE - TENANT DATABASE
-- FILE: 05_Policies.sql
-- ============================================================
GO

CREATE TABLE Policies (
    Id                      UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    TenantId                UNIQUEIDENTIFIER  NOT NULL,
    PolicyNumber            NVARCHAR(100)     NOT NULL,
    PolicyNumberNCC         NVARCHAR(100)     NULL,
    ReconcileCode           NVARCHAR(100)     NULL,
    QuotationId             UNIQUEIDENTIFIER  NULL REFERENCES Quotations(Id),
    PipelineId              UNIQUEIDENTIFIER  NULL REFERENCES SalesPipeline(Id),
    MasterProductId         UNIQUEIDENTIFIER  NOT NULL,
    ProductPlanId           UNIQUEIDENTIFIER  NULL,
    ProviderId              UNIQUEIDENTIFIER  NOT NULL,
    InsuranceType           NVARCHAR(50)      NOT NULL,
    CustomerId              UNIQUEIDENTIFIER  NOT NULL REFERENCES Customers(Id),
    InsuredName             NVARCHAR(255)     NULL,
    InsuredIdCard           NVARCHAR(20)      NULL,
    InsuredDOB              DATE              NULL,
    InsuredPhone            NVARCHAR(20)      NULL,
    InsuredRelationship     NVARCHAR(50)      NULL,
    InsuredObjectData       NVARCHAR(MAX)     NOT NULL,
    StartDate               DATE              NOT NULL,
    EndDate                 DATE              NOT NULL,
    DurationDays            INT               NOT NULL,
    BasePremium             DECIMAL(18,2)     NOT NULL,
    DiscountAmount          DECIMAL(18,2)     NOT NULL DEFAULT 0,
    SurchargeAmount         DECIMAL(18,2)     NOT NULL DEFAULT 0,
    FinalPremium            DECIMAL(18,2)     NOT NULL,
    PaymentInstallments     INT               NOT NULL DEFAULT 1,
    InstallmentAmount       DECIMAL(18,2)     NULL,
    InsuredAmount           DECIMAL(18,2)     NULL,
    SaleChannel             NVARCHAR(30)      NOT NULL,
    AgentId                 UNIQUEIDENTIFIER  NOT NULL REFERENCES Agents(Id),
    LandingPageId           UNIQUEIDENTIFIER  NULL,
    PolicyStatus            NVARCHAR(30)      NOT NULL DEFAULT 'DRAFT',
    PolicyStatusChangedAt   DATETIME2         NULL,
    PolicyStatusChangedBy   UNIQUEIDENTIFIER  NULL,
    PaymentStatus           NVARCHAR(20)      NOT NULL DEFAULT 'UNPAID',
    TotalPaid               DECIMAL(18,2)     NOT NULL DEFAULT 0,
    BalanceDue              DECIMAL(18,2)     NOT NULL DEFAULT 0,
    ProviderStatus          NVARCHAR(20)      NULL,
    ProviderSubmittedAt     DATETIME2         NULL,
    ProviderConfirmedAt     DATETIME2         NULL,
    ProviderRejectedAt      DATETIME2         NULL,
    ProviderRejectedReason  NVARCHAR(500)     NULL,
    ProviderResponse        NVARCHAR(MAX)     NULL,
    ReconciliationStatus    NVARCHAR(30)      NULL,
    ReconciliationPeriod    NVARCHAR(10)      NULL,
    ReconciledAt            DATETIME2         NULL,
    CommissionStatus        NVARCHAR(20)      NOT NULL DEFAULT 'PENDING',
    CommissionPaidAt        DATETIME2         NULL,
    CommissionBatchId       UNIQUEIDENTIFIER  NULL,
    RenewalStatus           NVARCHAR(20)      NULL,
    PreviousPolicyId        UNIQUEIDENTIFIER  NULL REFERENCES Policies(Id),
    RenewalPolicyId         UNIQUEIDENTIFIER  NULL REFERENCES Policies(Id),
    RenewalReminderSentAt   DATETIME2         NULL,
    RenewalReminderCount    INT               NOT NULL DEFAULT 0,
    ContractPdfUrl          NVARCHAR(500)     NULL,
    CertificatePdfUrl       NVARCHAR(500)     NULL,
    InvoiceUrl              NVARCHAR(500)     NULL,
    CancelledAt             DATETIME2         NULL,
    CancelReason            NVARCHAR(50)      NULL,
    CancelNote              NVARCHAR(500)     NULL,
    CancelledBy             UNIQUEIDENTIFIER  NULL,
    RefundAmount            DECIMAL(18,2)     NULL,
    Notes                   NVARCHAR(MAX)     NULL,
    InternalNotes           NVARCHAR(MAX)     NULL,
    Tags                    NVARCHAR(500)     NULL,
    CreatedAt               DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy               UNIQUEIDENTIFIER  NULL,
    UpdatedAt               DATETIME2         NULL,
    UpdatedBy               UNIQUEIDENTIFIER  NULL,
    IsDeleted               BIT               NOT NULL DEFAULT 0,
    CONSTRAINT PK_Policies PRIMARY KEY (Id),
    CONSTRAINT UQ_Policies_Number UNIQUE (TenantId, PolicyNumber)
);
GO

CREATE TABLE PolicyStatusHistory (
    Id            BIGINT            NOT NULL IDENTITY(1,1),
    PolicyId      UNIQUEIDENTIFIER  NOT NULL REFERENCES Policies(Id),
    TenantId      UNIQUEIDENTIFIER  NOT NULL,
    OldStatus     NVARCHAR(30)      NULL,
    NewStatus     NVARCHAR(30)      NOT NULL,
    ChangeReason  NVARCHAR(500)     NULL,
    ChangedBy     UNIQUEIDENTIFIER  NULL,
    ChangedByType NVARCHAR(20)      NULL,
    Notes         NVARCHAR(MAX)     NULL,
    ChangedAt     DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_PolicyStatusHistory PRIMARY KEY (Id)
);
GO

CREATE TABLE PolicyDocuments (
    Id          UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
    PolicyId    UNIQUEIDENTIFIER  NOT NULL REFERENCES Policies(Id),
    TenantId    UNIQUEIDENTIFIER  NOT NULL,
    DocType     NVARCHAR(50)      NOT NULL,
    DocName     NVARCHAR(255)     NULL,
    FileUrl     NVARCHAR(500)     NOT NULL,
    FileSize    BIGINT            NULL,
    MimeType    NVARCHAR(100)     NULL,
    Source      NVARCHAR(20)      NULL,
    IsVerified  BIT               NOT NULL DEFAULT 0,
    UploadedBy  UNIQUEIDENTIFIER  NULL,
    UploadedAt  DATETIME2         NOT NULL DEFAULT GETUTCDATE(),
    IsActive    BIT               NOT NULL DEFAULT 1,
    CONSTRAINT PK_PolicyDocuments PRIMARY KEY (Id)
);
GO
